import { Ticket, AnalyticsData, AILog } from './types';

export const MOCK_TICKETS: Ticket[] = [
  {
    _id: '1',
    ticketId: 'KF-2024-001',
    farmerName: 'Ramesh Kumar',
    phone: '+91 98765 43210',
    district: 'Nashik',
    state: 'Maharashtra',
    language: 'Hindi',
    crop: 'Tomato',
    issue: 'My tomato plants are showing yellow leaves and the fruits are not growing properly. The leaves have brown spots and are falling off.',
    severity: 'High',
    category: 'Crop Disease',
    status: 'In Review',
    assignedOfficer: 'Dr. Priya Sharma',
    department: 'Plant Protection',
    suggestedAction: 'Apply copper-based fungicide. Ensure proper drainage. Remove infected leaves immediately.',
    aiSummary: 'Farmer reports tomato crop showing symptoms consistent with early blight (Alternaria solani). Immediate fungicide application recommended.',
    createdAt: '2024-11-15T08:30:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
  },
  {
    _id: '2',
    ticketId: 'KF-2024-002',
    farmerName: 'Sunita Devi',
    phone: '+91 87654 32109',
    district: 'Amravati',
    state: 'Maharashtra',
    language: 'Marathi',
    crop: 'Cotton',
    issue: 'Cotton crop is being attacked by pink bollworm. Many bolls are damaged and I am losing my crop.',
    severity: 'Critical',
    category: 'Pest Attack',
    status: 'Escalated',
    assignedOfficer: 'Mr. Vijay Patil',
    department: 'Pest Management',
    suggestedAction: 'Emergency pheromone trap deployment. Apply recommended insecticide. Contact district agriculture office.',
    aiSummary: 'Critical pink bollworm infestation in cotton crop. Immediate intervention required to prevent total crop loss.',
    createdAt: '2024-11-14T14:20:00Z',
    updatedAt: '2024-11-15T09:15:00Z',
  },
  {
    _id: '3',
    ticketId: 'KF-2024-003',
    farmerName: 'Arjun Singh',
    phone: '+91 76543 21098',
    district: 'Pune',
    state: 'Maharashtra',
    language: 'Hindi',
    crop: 'Wheat',
    issue: 'Soil is very hard and water is not absorbing properly. Wheat seeds are not germinating well.',
    severity: 'Medium',
    category: 'Soil Health',
    status: 'Pending',
    department: 'Soil Science',
    suggestedAction: 'Conduct soil test. Add organic matter. Consider deep plowing before next season.',
    createdAt: '2024-11-15T11:00:00Z',
    updatedAt: '2024-11-15T11:00:00Z',
  },
  {
    _id: '4',
    ticketId: 'KF-2024-004',
    farmerName: 'Meena Bai',
    phone: '+91 65432 10987',
    district: 'Aurangabad',
    state: 'Maharashtra',
    language: 'Marathi',
    crop: 'Sugarcane',
    issue: 'Drip irrigation system is not working properly. Water pressure is low and some emitters are blocked.',
    severity: 'Medium',
    category: 'Irrigation',
    status: 'Resolved',
    assignedOfficer: 'Er. Suresh Jadhav',
    department: 'Irrigation Engineering',
    suggestedAction: 'Clean blocked emitters. Check pump pressure. Replace damaged drip lines.',
    aiSummary: 'Irrigation system maintenance required. Issue resolved after field visit and system repair.',
    createdAt: '2024-11-13T09:00:00Z',
    updatedAt: '2024-11-14T16:30:00Z',
  },
  {
    _id: '5',
    ticketId: 'KF-2024-005',
    farmerName: 'Prakash Rao',
    phone: '+91 54321 09876',
    district: 'Nagpur',
    state: 'Maharashtra',
    language: 'Telugu',
    crop: 'Orange',
    issue: 'Orange trees are not producing enough fruits. The leaves are pale and the tree looks weak.',
    severity: 'Low',
    category: 'Fertilizer',
    status: 'Resolved',
    assignedOfficer: 'Dr. Anita Kulkarni',
    department: 'Horticulture',
    suggestedAction: 'Apply micronutrient mix. Increase nitrogen fertilizer. Conduct leaf analysis.',
    aiSummary: 'Nutrient deficiency identified in orange orchard. Micronutrient supplementation recommended.',
    createdAt: '2024-11-12T10:30:00Z',
    updatedAt: '2024-11-13T14:00:00Z',
  },
  {
    _id: '6',
    ticketId: 'KF-2024-006',
    farmerName: 'Kavitha Reddy',
    phone: '+91 43210 98765',
    district: 'Solapur',
    state: 'Maharashtra',
    language: 'Kannada',
    crop: 'Soybean',
    issue: 'Unexpected hailstorm damaged my soybean crop. About 40% of the crop is destroyed.',
    severity: 'High',
    category: 'Weather',
    status: 'In Review',
    assignedOfficer: 'Mr. Ravi Deshmukh',
    department: 'Crop Insurance',
    suggestedAction: 'File crop insurance claim immediately. Document damage with photographs. Contact district collector office.',
    aiSummary: 'Weather-related crop damage. Insurance claim process initiated. Damage assessment team dispatched.',
    createdAt: '2024-11-15T07:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
  },
  {
    _id: '7',
    ticketId: 'KF-2024-007',
    farmerName: 'Balram Yadav',
    phone: '+91 32109 87654',
    district: 'Kolhapur',
    state: 'Maharashtra',
    language: 'Hindi',
    crop: 'Rice',
    issue: 'The seeds I bought from the market are not germinating. Only 30% germination rate.',
    severity: 'High',
    category: 'Seed Quality',
    status: 'Escalated',
    assignedOfficer: 'Dr. Sanjay Patil',
    department: 'Seed Certification',
    suggestedAction: 'Test seed germination rate. File complaint with seed supplier. Provide replacement seeds.',
    aiSummary: 'Poor seed quality detected. Seed certification authority notified. Replacement seeds being arranged.',
    createdAt: '2024-11-14T08:00:00Z',
    updatedAt: '2024-11-15T11:30:00Z',
  },
  {
    _id: '8',
    ticketId: 'KF-2024-008',
    farmerName: 'Geeta Sharma',
    phone: '+91 21098 76543',
    district: 'Jalgaon',
    state: 'Maharashtra',
    language: 'Hindi',
    crop: 'Banana',
    issue: 'Banana plants are showing signs of Panama disease. Leaves are yellowing and wilting.',
    severity: 'Critical',
    category: 'Crop Disease',
    status: 'In Review',
    assignedOfficer: 'Dr. Priya Sharma',
    department: 'Plant Protection',
    suggestedAction: 'Quarantine affected area. Remove and destroy infected plants. Apply soil fumigation.',
    aiSummary: 'Fusarium wilt (Panama disease) suspected. Immediate quarantine measures required to prevent spread.',
    createdAt: '2024-11-15T06:00:00Z',
    updatedAt: '2024-11-15T13:00:00Z',
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  totalTickets: 247,
  resolvedTickets: 189,
  escalatedCases: 23,
  pendingTickets: 35,
  avgResolutionTime: 2.4,
  categoryBreakdown: [
    { name: 'Crop Disease', value: 68, color: '#ef4444' },
    { name: 'Pest Attack', value: 52, color: '#f97316' },
    { name: 'Irrigation', value: 41, color: '#3b82f6' },
    { name: 'Soil Health', value: 35, color: '#8b5cf6' },
    { name: 'Fertilizer', value: 28, color: '#22c55e' },
    { name: 'Weather', value: 15, color: '#eab308' },
    { name: 'Seed Quality', value: 8, color: '#ec4899' },
  ],
  severityBreakdown: [
    { name: 'Low', value: 45, color: '#22c55e' },
    { name: 'Medium', value: 89, color: '#eab308' },
    { name: 'High', value: 78, color: '#f97316' },
    { name: 'Critical', value: 35, color: '#ef4444' },
  ],
  districtWise: [
    { district: 'Nashik', tickets: 42, resolved: 35 },
    { district: 'Pune', tickets: 38, resolved: 30 },
    { district: 'Nagpur', tickets: 35, resolved: 28 },
    { district: 'Aurangabad', tickets: 31, resolved: 25 },
    { district: 'Amravati', tickets: 28, resolved: 22 },
    { district: 'Solapur', tickets: 25, resolved: 20 },
    { district: 'Kolhapur', tickets: 22, resolved: 18 },
    { district: 'Jalgaon', tickets: 26, resolved: 11 },
  ],
  weeklyTrend: [
    { day: 'Mon', tickets: 18, resolved: 14 },
    { day: 'Tue', tickets: 22, resolved: 18 },
    { day: 'Wed', tickets: 15, resolved: 12 },
    { day: 'Thu', tickets: 28, resolved: 20 },
    { day: 'Fri', tickets: 32, resolved: 25 },
    { day: 'Sat', tickets: 20, resolved: 16 },
    { day: 'Sun', tickets: 12, resolved: 10 },
  ],
  monthlyTrend: [
    { month: 'Jun', tickets: 45, resolved: 38, escalated: 4 },
    { month: 'Jul', tickets: 62, resolved: 52, escalated: 6 },
    { month: 'Aug', tickets: 78, resolved: 65, escalated: 8 },
    { month: 'Sep', tickets: 55, resolved: 48, escalated: 5 },
    { month: 'Oct', tickets: 89, resolved: 72, escalated: 10 },
    { month: 'Nov', tickets: 95, resolved: 78, escalated: 12 },
  ],
};

export const MOCK_AI_LOGS: AILog[] = [
  {
    _id: '1',
    ticketId: 'KF-2024-001',
    operation: 'classify',
    prompt: 'Analyze: Tomato plants showing yellow leaves with brown spots, fruits not growing properly.',
    response: 'Classification: Crop Disease - Early Blight. Severity: High. Recommended action: Apply copper-based fungicide.',
    classification: {
      crop: 'Tomato',
      category: 'Crop Disease',
      issueCategory: 'Crop Disease',
      severity: 'High',
      department: 'Plant Protection',
      suggestedAction: 'Apply copper-based fungicide. Ensure proper drainage.',
      summary: 'Tomato plants showing Early Blight symptoms with yellow leaves and brown spots.',
      confidence: 0.94,
    },
    model: 'llama-3.3-70b-versatile',
    processingTimeMs: 1240,
    isMock: false,
    createdAt: '2024-11-15T08:30:05Z',
    updatedAt: '2024-11-15T08:30:05Z',
  },
  {
    _id: '2',
    ticketId: 'KF-2024-002',
    operation: 'classify',
    prompt: 'Analyze: Cotton crop attacked by pink bollworm, many bolls damaged.',
    response: 'Classification: Pest Attack - Pink Bollworm. Severity: Critical. Emergency intervention required.',
    classification: {
      crop: 'Cotton',
      category: 'Pest Attack',
      issueCategory: 'Pest Attack',
      severity: 'Critical',
      department: 'Pest Management',
      suggestedAction: 'Emergency pheromone trap deployment. Apply recommended insecticide.',
      summary: 'Cotton crop severely attacked by pink bollworm with many bolls damaged.',
      confidence: 0.97,
    },
    model: 'llama-3.3-70b-versatile',
    processingTimeMs: 980,
    isMock: false,
    createdAt: '2024-11-14T14:20:08Z',
    updatedAt: '2024-11-14T14:20:08Z',
  },
];

export const SUPPORTED_LANGUAGES = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'en', name: 'English', nativeName: 'English' },
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Gujarat',
  'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
  'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan',
  'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

export const MAHARASHTRA_DISTRICTS = [
  'Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara',
  'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli',
  'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban',
  'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar',
  'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara',
  'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal',
];
